[phases.setup]
nixPkgs = ["python311", "ffmpeg"]
aptPkgs = [
    "libglib2.0-0",
    "libnss3",
    "libnspr4",
    "libdbus-1-3",
    "libatk1.0-0",
    "libatk-bridge2.0-0",
    "libcups2",
    "libdrm2",
    "libatspi2.0-0",
    "libx11-6",
    "libxcomposite1",
    "libxdamage1",
    "libxext6",
    "libxfixes3",
    "libxrandr2",
    "libgbm1",
    "libxcb1",
    "libxkbcommon0",
    "libpango-1.0-0",
    "libcairo2",
    "libasound2"
]

[phases.build]
cmds = ["pip install -r requirements.txt", "playwright install chromium"]

[start]
cmd = "python main.py"
